blank_issues_enabled: false
contact_links:
  - name: Discord Community
    url: https://discord.gg/CkD9QWjsHm
    about: Ask questions and get help from the community on Discord.
  - name: WhatsApp Group
    url: https://chat.whatsapp.com/Hpx42q1ADsrFNN3hHtZcQa
    about: Join the WhatsApp community group.
