/**
 * Event branding, one per cohort.
 *
 * The export pipeline was built around a single hardcoded event: the July
 * Impact Lab. That held for as long as this system produced results for one
 * event. It does not survive the second one — the Afretec Makerthon results
 * report is generated by the same pipeline, for a different host, on a
 * different date, and it must not print July's facts on August's document.
 *
 * Same shape as `./judging-rubrics`: a constant per cohort, resolved by a
 * function, defaulting rather than throwing on an unknown cohort. A DB-backed
 * override can replace the lookup table later without touching call sites.
 */

/** The facts an export prints about the event it covers. */
export interface EventBranding {
  /** Cover title split for the two-tone treatment. */
  titleLead: string
  titleAccent: string
  /** One-line title for prose, spreadsheet facts and metadata. */
  title: string
  dates: string
  /** Whose event it is. */
  host: string
  location: string
  formatNote: string
  /** Who ran the platform, when that differs from the host. Optional. */
  platformNote?: string
}

/**
 * Who generates the report, as distinct from whose event it was.
 *
 * These come apart the moment the platform runs somebody else's event. The
 * report is produced by this platform from the host's operational records —
 * saying the host produced it would be a false provenance claim in a document
 * that an external organisation reads and may forward on.
 */
export const REPORT_PRODUCER = "Claude Community Kenya"

// ─── Impact Lab (Claude Community Kenya) ─────────────────────────────────────

/** The original event facts, unchanged in behaviour. */
export const IMPACT_LAB_BRANDING: EventBranding = {
  titleLead: "Impact Lab:",
  titleAccent: "AI Mashinani",
  title: "Impact Lab: AI Mashinani",
  dates: "25–26 July 2026",
  host: "Claude Community Kenya",
  location: "Nairobi, Kenya",
  formatNote:
    "An overnight build: teams formed in the evening, built through the night, " +
    "and judging ran from the small hours into the morning.",
}

// ─── Afretec Makerthon 2026 (C4DLab, University of Nairobi) ──────────────────

/**
 * C4DLab's own hackathon, run on the Impact Lab platform. The event's facts —
 * host, dates, format — are C4DLab's, not Claude Community Kenya's; the
 * report goes to an external organisation and must say so.
 */
export const AFRETEC_BRANDING: EventBranding = {
  titleLead: "Afretec",
  titleAccent: "Makerthon 2026",
  title: "Afretec Makerthon 2026",
  dates: "8 August 2026",
  host: "C4DLab, University of Nairobi",
  location: "Nairobi, Kenya",
  formatNote:
    "Teams registered as existing startups and were formed before the event. Each team " +
    "pitched live for five minutes and was scored by a judging panel on eight criteria out " +
    "of 50.",
  platformNote: "Run on the Impact Lab platform by Claude Community Kenya",
}

// ─── Resolution ──────────────────────────────────────────────────────────────

/**
 * Cohort → branding. A cohort absent from this map is branded as the Impact
 * Lab event, which is the right default: every export produced before this
 * system knew about a second event was for that one.
 */
const BRANDING_BY_COHORT: Readonly<Record<string, EventBranding>> = {
  "afretec-makerthon-2026-08": AFRETEC_BRANDING,
}

/**
 * The branding a cohort's exports print.
 *
 * Never throws on an unknown cohort — an organiser generating a report mid
 * event must not hit an error page because a slug was typed differently
 * somewhere. An unknown cohort gets the Impact Lab branding.
 */
export function brandingForCohort(cohort: string): EventBranding {
  return BRANDING_BY_COHORT[cohort] ?? IMPACT_LAB_BRANDING
}
