#!/usr/bin/env bash
# Generate a migration by diffing the live database against schema.prisma.
#
# Why this exists instead of `prisma migrate dev`: this repo's databases carry
# real data, and `migrate dev` responds to anything it cannot account for by
# offering to reset — which drops every row. It also cannot account for the
# partial index registered in docs/database/unrepresentable-objects.md, so it
# hits that case every single run.
#
# This script does the diff, removes exactly the registered lines, and refuses
# to write a migration if the diff contains any other destructive statement.
# A DROP you did not intend is the failure mode worth being loud about.
#
#   bash scripts/new-migration.sh add_widget_flags
set -euo pipefail

NAME="${1:-}"
if [ -z "$NAME" ]; then
  echo "usage: bash scripts/new-migration.sh <snake_case_name>" >&2
  exit 1
fi
if ! printf %s "$NAME" | grep -qE '^[a-z][a-z0-9_]*$'; then
  echo "name must be snake_case: [a-z][a-z0-9_]*" >&2
  exit 1
fi

# Objects Prisma cannot express. Keep in step with
# docs/database/unrepresentable-objects.md — one grep pattern per entry.
UNREPRESENTABLE='impact_lab_match_runs_one_final_per_cohort'

STAMP="$(date -u +%Y%m%d%H%M%S)"
DIR="prisma/migrations/${STAMP}_${NAME}"
[ -e "$DIR" ] && { echo "$DIR already exists" >&2; exit 1; }

RAW="$(mktemp)"; trap 'rm -f "$RAW"' EXIT
npx prisma migrate diff \
  --from-config-datasource \
  --to-schema prisma/schema.prisma \
  --script > "$RAW"

if ! grep -qE '[A-Za-z]' "$RAW"; then
  echo "No changes — schema.prisma already matches the database."
  exit 0
fi

# Strip the registered objects, then audit what is left.
CLEAN="$(grep -vE "$UNREPRESENTABLE" "$RAW" | grep -vE '^-- (Drop|Create)Index$' || true)"

DESTRUCTIVE="$(printf %s "$CLEAN" | grep -inE '^\s*(DROP|ALTER TABLE .* DROP|TRUNCATE)' || true)"
if [ -n "$DESTRUCTIVE" ]; then
  echo
  echo "REFUSING TO WRITE — the diff contains destructive statements that are not"
  echo "in the unrepresentable-objects register:"
  echo
  printf '%s\n' "$DESTRUCTIVE"
  echo
  echo "Either they are intentional — in which case write the migration by hand"
  echo "and say why in a header comment — or something has drifted. Check with:"
  echo "  npx prisma migrate diff --from-migrations ./prisma/migrations \\"
  echo "    --to-config-datasource --script   (needs SHADOW_DATABASE_URL)"
  exit 2
fi

mkdir -p "$DIR"
{
  echo "-- ${NAME}"
  echo "--"
  echo "-- Generated by scripts/new-migration.sh. Registered unrepresentable"
  echo "-- objects were stripped; see docs/database/unrepresentable-objects.md."
  echo
  printf '%s\n' "$CLEAN"
} > "$DIR/migration.sql"

echo "Wrote $DIR/migration.sql"
echo "Read it, then apply with:  npx prisma migrate deploy"
